package activities;

import java.util.ArrayList;
import java.util.List;
import java.util.Random;
import java.util.Scanner;

public class Activity12 {
public static void main(String[] args) {
	List<Integer> list=new ArrayList<>();
	Scanner scan=new Scanner(System.in);
	System.out.println("size of the array is: ");
	int arraySize=scan.nextInt();
	System.out.println("Enter array elements: ");
	for(int i=0;i<arraySize;i++) {
		list.add(scan.nextInt());
	}
	
	int max=arraySize-1;
	int min=1;
	Random indexGen=new Random();
	 int randomindexVal = indexGen.nextInt((max - min) + 1) + min;

	System.out.println("The value generated by random generator at index "+randomindexVal+ " is: "+list.get(randomindexVal));
	
}
}

